# -*- coding: utf-8 -*-
"""ЛР1_Пачи_ПИ24-2в_сем4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pyHskok9RGLW7BTTbOaPr0b45yo627Vn

# Практическая работа "Парсинг данных и работа с внешними API".

## 1. Парсинг новостей с веб-сайта.
"""

import re
import requests
import csv
from bs4 import BeautifulSoup
from urllib.parse import urljoin

url = "https://lenta.ru"

# проверка статуса страницы
def check_site(url):
    try:
        response = requests.head(url, timeout=5)
        return response.status_code < 500
    except requests.RequestException:
        return False

if check_site(url):
  print("Сайт доступен, можно парсить")

  # получение HTML-кода страницы
  response = requests.get(url)

  # создание парсируемого объекта
  soup = BeautifulSoup(response.text, 'lxml')

  # нахождение всех ссылок, начинающихся с card, но без '__' - это блоки с новостями
  cards = soup.find_all(class_=re.compile(r"^card-[a-z]+$"))  #  префикса card- и затем только строчных букв


else:
  print("Сайт недоступен, попробуйте позже.")

# получение всех новостей
def get_news():
    all_news = []
    n = 1

    for card in cards:
        title_tag = card.find("h3")
        if not title_tag:
            continue

        title = title_tag.get_text(strip=True)
        link = urljoin(url, card.get("href")) # объединяет базовый URL и относительный путь

        all_news.append(f"{n}. {title}: {link}\n")
        n += 1

    return all_news

# сохрание в файл данных о новостях
def save_news():
  with open("all_news_from_lenta_ru.txt", "w", encoding="utf-8") as f:
    f.writelines(get_news())

  print("Данные записаны в файл all_news_from_lenta_ru.txt")

# сохрание в файл данных о новостях csv
def save_news_csv(filename="all_news_from_lenta_ru.csv"):
    news = get_news()

    with open(filename, "w", encoding="utf-8", newline="") as f:
        fieldnames = ["№", "title", "link"]
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        for item in news:
            writer.writerow(item)

# ввывод в в консоль
print(*get_news())
